eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql20apr2021
    url: jdbc:mysql://localhost:3306/javatechie
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
resilience4j:
  circuitbreaker:
    instances:
        orderService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: count-based
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            automatic-transition-from-open-to-half-open-enabled: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: C:/Users/SAGAR/Desktop/ELK/order-payment-common.log
  level:
    com: 
      javatechie: DEBUG
      
